spring.application.name=Spring-AI
server.port=9292

logging.level.org.springframework.ai.chat.client.advisor=DEBUG


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spring_ai
spring.datasource.username=root
spring.datasource.password=qwerty
spring.jpa.show-sql=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS